### ISSUE TITLE
Implement POST /processPartnership and trigger it from Front-end

### ISSUE THREAD

**Issue by kshpdr** [ADSP-Project/Federation-Service#2]
**Task description**
We want to introduce new endpoint that is gonna receive a partnerId and a flag whether request is approved or not. As a result requestStatus in partners table has to be changed.

We also want to get two buttons (Approve / Deny) working so they have to trigger this endpoint.

**Comment by georgyrudnev** [comment]
@kshpdr "we need to get two buttons (Approve / Deny) working so they have to trigger this endpoint." - these two buttons will need to be introduced in the UI for shop.go in Federation hub, right?

**Comment by vuxtojkovic** [comment]
@georgyrudnev:
I will push latest changes to main, which have those two buttons on route ".../partners".
Here #4 you see that both of them are invoking certain functions which you can write and I'll take care that they are properly used in UI.
![image](https://github.com/ADSP-Project/Federation-Service/assets/71947247/d2dd71c4-c143-4a6b-8d09-40f49a59810b)
