### ISSUE TITLE
Implement partnership request as a JWT endpoint

### ISSUE THREAD

**Issue by georgyrudnev** [ADSP-Project/Federation-Service#6]
1. Shop.go gets JWT request with JWT token from other shop
2. Shop.go needs to verify authentication of other shop by verifying received token using public key from hub
3. If verification is successful, shop.go adds other shop to partnerDatabase

Need to discuss further where approval/denial (frontend) comes to play here

**Comment by georgyrudnev** [comment]
@kshpdr  @stojkovicv  can you advise on last point?

**Comment by kshpdr** [comment]
@georgyrudnev basically we should have an api call in frontend when pushing the button. Approve would be true then in body (e.g. approved: true) and deny would be.(approved: false)

**Comment by kshpdr** [comment]
Closing since implemented already in the request body.
