### ISSUE TITLE
Wrong partners shown on main page & partners view

### ISSUE THREAD

**Issue by georgyrudnev** [ADSP-Project/Federation-Service#9]
Currently in the dashboard you are only seeing your own shop and if you try to request partnership with another shop, the other shop does not see the request in it´s dashboard.

Todo: 1. Get to run the shop.go on different machines so we have different databases
2. Change the code so that correct shops will see partnership requests and only requested party is able to approve/deny

**Comment by kshpdr** [comment]
Fixed in https://github.com/ADSP-Project/Federation-Service/pull/10
